### ISSUE TITLE
Checklist # 3

### ISSUE THREAD

**Issue by elisawarner** [elisawarner/Google_Scholar_Comparator#3]
- [x] Store data in 2 different database tables (using SQL)
- [x] Each table should have at least 2 columns and at least 4 rows
- [x] At least one relationship should exist between them
